// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Web OAuth client (type 3 in `google-services.json`).
  /// Required as [GoogleSignIn] `serverClientId` on Android so Firebase receives an ID token.
  static const String googleWebClientId =
      '299243495312-hm7fpugq207ono5m3ack4pv9djar8e5s.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZcrDLCPFu3tOs5tLAa6j-FeGll_MCa9k',
    appId: '1:299243495312:android:a8f07df49f516cdee35d15',
    messagingSenderId: '299243495312',
    projectId: 'todai-c076f',
    storageBucket: 'todai-c076f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5xg1B6hIv9ouDD9x3yaxP4yO5KLAYoNg',
    appId: '1:299243495312:ios:5ae6d50a6f375b62e35d15',
    messagingSenderId: '299243495312',
    projectId: 'todai-c076f',
    storageBucket: 'todai-c076f.firebasestorage.app',
    iosClientId:
        '299243495312-9k28khsh1t57tq1hf43cstf387vd344i.apps.googleusercontent.com',
    iosBundleId: 'com.todayapp.today',
  );
}
